rows = [
 ('T21','Phillips Curve','Theory','Economics','Global','Verified (contested)','','C30;C28','',''),
 ('T22','Fisher Effect','Theory','Economics','Global','Verified','','C28;C10','',''),
 ('T23','Purchasing Power Parity','Theory','Economics','Global','Verified (contested)','A07','','',''),
 ('T24','Random Walk Theory','Theory','Quantitative Methods','Global','Verified','','T02(semantic-extends,F3)','',''),
 ('T25','Uncovered Interest Rate Parity','Theory','Economics','Global','Verified (contested)','A07','','',''),
 ('M21','Taylor Rule Model','Model','Economics','Global','Verified','F26','C32;C28','',''),
 ('M22','IS-LM Model','Model','Economics','Global','Verified','','C29;C32;C33','',''),
 ('M23','Ho-Lee Interest Rate Model','Model','Fixed Income','Global','Verified','M05(semantic-extends,F3)','','',''),
 ('M24','Black-Derman-Toy Model','Model','Fixed Income','Global','Verified','M23(semantic-extends,F3)','','',''),
 ('F26','Taylor Rule Formula','Formula','Economics','Global','Verified','','','',''),
 ('F27','Fisher Equation','Formula','Economics','Global','Verified','','','',''),
 ('F28','Covered Interest Rate Parity Formula','Formula','Derivatives','Global','Verified','','','',''),
 ('F29','Black-Litterman Formula','Formula','Portfolio Management','Global','Verified','','','',''),
 ('F30','Kelly Criterion Formula','Formula','Portfolio Management','Global','Verified','','','',''),
 ('ME44','Real Interest Rate','Metric','Economics','Global','Verified','F27','C28','',''),
 ('ME46','Sharpe-to-Drawdown Ratio','Metric','Portfolio Management','Global','Provisional','','C64','',''),
 ('ME47','ESG Score','Metric','Alternative Investments','Global','Provisional','','','',''),
 ('ME48','Expense Ratio','Metric','Alternative Investments','Global','Verified','','','',''),
 ('PR26','Liquidity Ratio Analysis','Procedure','Financial Statement Analysis','Global','Verified','','ME26;ME27','',''),
 ('PR27','Profitability Ratio Analysis','Procedure','Financial Statement Analysis','Global','Verified','','ME30;ME31;ME32','',''),
 ('PR28','Insider Trading Compliance Review','Procedure','Ethical and Professional Standards','Global','Verified','','C36','S03(semantic-standardimpl)',''),
 ('PR29','Conflict of Interest Disclosure Procedure','Procedure','Ethical and Professional Standards','Global','Verified','','C35','S03(semantic-standardimpl)',''),
 ('PR30','ESG Integration Screening','Procedure','Alternative Investments','Global','Verified','ME47','','',''),
 ('PR31','Currency Hedging via Forward Contracts','Procedure','Derivatives','Global','Verified','F28','','',''),
 ('PR32','Black-Litterman Portfolio Optimization','Procedure','Portfolio Management','Global','Verified','F29','','',''),
 ('PR33','Kelly Criterion Position Sizing','Procedure','Portfolio Management','Global','Provisional','F30','','',''),
 ('PR34','Working Capital Management','Procedure','Corporate Issuers','Global','Verified','','C37','',''),
 ('PR35','Anti-Money Laundering Screening','Procedure','Ethical and Professional Standards','Global','Verified','','','S07(semantic-standardimpl)',''),
 ('C56','Term Premium','Concept','Fixed Income','Global','Verified','','','',''),
 ('C57','Roll-Down Return','Concept','Fixed Income','Global','Verified','','','',''),
 ('C58','Sovereign Risk','Concept','Fixed Income','Global','Verified','','','',''),
 ('C59','Contango','Concept','Derivatives','Global','Verified','','','',''),
 ('C60','Backwardation','Concept','Derivatives','Global','Verified','','','',''),
 ('C61','Implied Correlation','Concept','Derivatives','Global','Verified','','','',''),
 ('C62','ESG Integration','Concept','Alternative Investments','Global','Verified','','','',''),
 ('C63','Lock-Up Period','Concept','Alternative Investments','Global','Verified','','','',''),
 ('C64','Drawdown','Concept','Portfolio Management','Global','Verified','','','',''),
 ('C65','Tail Risk','Concept','Portfolio Management','Global','Verified','','','',''),
 ('A16','Covered Interest Rate Parity Holds','Assumption','Derivatives','Global','Verified','','','',''),
 ('A17','No Model Risk','Assumption','Quantitative Methods','Global','Disputed','','','',''),
 ('A18','Stable Regulatory Environment','Assumption','Ethical and Professional Standards','Global','Provisional','','','',''),
 ('S16','FATCA','Standard','Ethical and Professional Standards','US','Verified','','','',''),
 ('S17','Volcker Rule','Standard','Ethical and Professional Standards','US','Verified','','','',''),
 ('S18','Common Reporting Standard','Standard','Ethical and Professional Standards','Global','Verified','','','',''),
 ('FR14','Three Lines of Defense','Framework','Ethical and Professional Standards','Global','Verified','','','',''),
 ('FR15','ESG Materiality Framework','Framework','Alternative Investments','Global','Verified','','C62','',''),
 ('FR16','Liquidity Ladder Framework','Framework','Fixed Income','Global','Verified','','C57','',''),
 ('PA11','Contango Roll Yield Drag','Pattern','Derivatives','Global','Verified','','C59','',''),
 ('PA12','ESG Premium Persistence','Pattern','Alternative Investments','Global','Disputed','','C62','',''),
]
with open(r'C:\Users\user\Desktop\faos\knowledge_seed_v0.2.psv', 'a', encoding='utf-8') as f:
    for r in rows:
        f.write('|'.join(r) + '\n')
print('Appended', len(rows), 'rows')
